# vim:ft=yaml.ansible
---
- name: Setup web server
  hosts: example
  vars:
    deb_architecture: { "aarch64": "arm64", "x86_64": "amd64" }
    user_name: runner
  roles:
    - docker
    - user
    - shell
    - firewall
